name: tcloset
description: "A Flutter closet app for managing wardrobe digitally"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.5
  
  # Data Models and Code Generation
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  
  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # UUID Generation
  uuid: ^4.5.1
  
  # Camera and Image
  camera: ^0.11.0+2
  image_picker: ^1.1.2
  image: ^4.2.0
  flutter_image_compress: ^2.3.0
  
  # File System
  path_provider: ^2.1.4
  path: ^1.9.0
  flutter_dotenv: ^5.1.0
  
  # Shared Preferences
  shared_preferences: ^2.3.2
  
  # UI Components
  cupertino_icons: ^1.0.8
  camera_avfoundation: ^0.9.20+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # Code Generation
  build_runner: ^2.4.12
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - .env
